gensec/blog/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'blog'

urlpatterns = [
url(r'^posts/$',views.PostListView.as_view(),name='post_list'),
url(r'^ongoing/$',views.EventListView.as_view(),name='event_list'),
url(r'^secreply/(?P<pk>\d+)/$',views.ReplyComment, name='reply_secretary'),
url(r'^$',views.HomeView.as_view(),name='home'),



]

gensec/gensec/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views

# from django.urls import path

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^accounts/logout/$', auth_views.logout, name = 'logout', kwargs = {'next_page':'/'}),
]

gensec/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.urls import reverse
# Create your models here.
User = get_user_model()

class Post(models.Model):
    author = models.ForeignKey(User, on_delete = models.CASCADE)
    title = models.CharField(max_length = 200)
    text = models.TextField()
    upvote = models.IntegerField(default=0)
    implemented = models.BooleanField(default=False)
    created_date = models.DateTimeField(default = timezone.now)
    published_date = models.DateTimeField( blank=True, null = True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs = {'pk':self.pk})

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete = models.CASCADE)
    parent_comment = models.ForeignKey("self", related_name='parent', on_delete = models.CASCADE, null=True, blank =True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)


    def get_absolute_url(self):
        return reverse("post_list")

    def children(self): #replies
        return Comment.objects.filter(parent=self)

    def __str__(self):
        return self.text

class Event(models.Model):
    created_date = models.DateField()
    finished_date = models.DateField(null = True, blank = True)
    title = models.CharField(max_length = 50)
    text = models.CharField(max_length = 300)

    def __str_(self):
        return self.title

class TimePoint(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name='timepoints')
    date = models.DateField()
    text = models.CharField(max_length = 100)

    def __str__(self):
        return self.event.title

# class Secretary(models.Model):
#     status = models.ForeignKey(Comment, on_delete=models.CASCADE)

gensec/blog/forms.py
from django import forms

from .models import Comment

class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

gensec/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from blog.models import Post, Event, Comment
from django.utils import timezone
from django.contrib.auth.decorators import user_passes_test

from django.views.generic import (TemplateView,ListView,
                                  DetailView,CreateView,
                                  UpdateView,DeleteView)
from django.contrib.auth import get_user_model
from .forms import CommentReplyForm

from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
User = get_user_model()
# Create your views here.

class HomeView(TemplateView):
    template_name = 'blog/home.html'


class PostListView(ListView):
    model = Post
    context_object_name = 'posts'
    template_name = 'blog/posts.html'

class EventListView(ListView):
    model = Event
    context_object_name = 'events'
    template_name = 'blog/events/events.html'

@user_passes_test(lambda u: u.is_superuser)
def ReplyComment(request, pk):
    parent = get_object_or_404(Comment, pk=pk)
    post = parent.post
    if request.method == "POST":
        form = CommentReplyForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.parent_comment = parent
            comment.save()
            return redirect('blog:post_list')
    else:
        form = CommentReplyForm()
    return render(request, 'blog/comment_reply_form.html', {'form': form})





    # def get_queryset(self):
    #     # super().get_queryset()
    #     return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

gensec/blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>
      {% block title %}

      {% endblock %}
    </title>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'blog/css/blog.css' %}">
    <script
      src="https://code.jquery.com/jquery-3.3.1.min.js"
      integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
      crossorigin="anonymous"></script>
      <!-- Compiled and minified JavaScript -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
     <meta name="viewport" content="width=device-width, iniial-scale=1">

  </head>
  <body>

    <div class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <a href="{% url 'blog:home' %}" class="brand-logo">GenSec</a>
          <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
          <ul class="right hide-on-med-and-down">
            <li><a href="{% url 'blog:event_list' %}">Ongoing Work</a></li>
            <li><a href="{% url 'blog:post_list' %}">Suggestions/Complaints</a></li>
            <li><a href="{% url 'blog:home' %}">Home</a></li>

          </ul>
        </div>
      </nav>

    </div>

    <ul class="sidenav" id="mobile-demo">
      <li><a href="{% url 'blog:event_list' %}">Ongoing Work</a></li>
      <li><a href="{% url 'blog:post_list' %}">Suggestions/Complaints</a></li>
      <li><a href="{% url 'blog:home' %}">Home</a></li>
    </ul>


    {% block content %}

    {% endblock %}

    <br><br><br><br>
    <footer class="page-footer">
      <div class="container">
        <div class="row">
          <div class="col l6 s12">
            <div class="row">
             <div class="col">
               <a href="{% url 'blog:post_list'%}" class="grey-text text-lighten-4">Suggestions/Complaints</a>
             </div>
             <div class="col">
               <a href="{% url 'blog:event_list'%}" class="grey-text text-lighten-4">Ongoing Work</a>
             </div>
            </div>
            <br>
            <div >
              <p class="grey-text text-lighten-4">DISCLAIMER: All data used on this site is fictitious and for representational
                 purposes only. </p>
            </div>
          </div>
          <div class="col l4 offset-l2 s12">
            <h5 class="white-text">Ask me anything!</h5>
            <ul>
              <li> <p class = "grey-text text-lighten-3"> Email: nihalshetty013@gmail.com</p>  </li>
              <li> <p class = "grey-text text-lighten-3"> Phone: +91 9482260459</p>  </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="footer-copyright">
        <div class="container">
        © ShettyForGenSec 2018
        </div>
      </div>
    </footer>

<script>
$(document).ready(function(){
  $('.sidenav').sidenav();
});
</script>


  </body>
</html>

gensec/blog/templates/blog/comment_detail.html
<blockquote class="blockquote mb-0" style="margin-bottom:0px; margin-top:0px;">
  {% if request.user.is_superuser %}
  <a href="{% url 'blog:reply_secretary' pk=comment.pk %}">{{comment.text}}</a>
  {% else %}
  <p>{{comment.text}}</p>
  {% endif %}
  <footer class="blockquote-footer"> <cite title="Source Title">- {{comment.author.first_name}} {{comment.author.last_name}}</cite></footer>
</blockquote>

gensec/blog/templates/blog/comment_reply_form.html
{% extends "blog/base.html" %}

{% block content %}
<div class="container">
  <form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn waves-effect waves-light">Submit</button>
  </form>
</div>

{% endblock %}

gensec/blog/templates/blog/comments.html
<ul class="collection with-header">
  {% for comment in comments.all %}
  {% if comment.parent_comment == None and not comment.author.is_superuser %}
    <li class="collection-item" style="margin:8px;">{% include "blog/comment_detail.html" with comment=comment%}</li>
  {% endif %}
  {% endfor %}
</ul>

gensec/blog/templates/blog/events/event_detail.html
<div class="card post-detail">


  <div class="card-content post-detail-content">
    <div>
      <span class="card-title">{{event.title}}</span>
      <p class="float right"> Started on: {{event.created_date}}</p>
      {% if event.finished_date %}
      <p class="float right"> Completed on:{{event.finished_date}}</p>
      {% else %}
      {% endif %}
    </div>
    <br>
    <p>{{event.text}}</p>
  </div>

  <div class="card-reveal">
    <span class="card-title grey-text text-darken-4">Timeline<i class="material-icons right">close</i></span>
    <div class="reveal-html">
        {% include "blog/events/timeline.html" with timepoints=event.timepoints %}
    </div>
  </div>


  <div class="card-tabs">
    <ul class="tabs tabs-fixed-width">
      <li class="tab"><a class="timeline activator com">Timeline</a></li>
    </ul>
  </div>






</div>

gensec/blog/templates/blog/events/events.html
{% extends "blog/base.html" %}


{% block content %}



<div class="container">
  <h2>Ongoing Work</h2>

  <div class="container suggestions-text">
  <h3 style="margin:2% 0 1% 5%;">What's this?</h3>
  <div >
    <p class="text-usage">Students can view all ongoing events along with those that have been finished.</p>
    <p class="text-usage">The timeline shows subsections of work completed on the respective dates.</p>
  </div>



  </div>

   {% for event in events %}
       {% include "blog/events/event_detail.html" with event=event %}
   {% endfor %}
</div>
{% endblock %}

gensec/blog/templates/blog/events/timeline.html
<ul class="collection with-header">
  {% for timepoint in timepoints.all %}
    <li class="collection-item">{% include "blog/events/timepoint.html" with timepoint=timepoint%}</li>
  {% endfor %}
</ul>

gensec/blog/templates/blog/events/timepoint.html
<blockquote class="blockquote mb-0">
  <p>{{timepoint.text}}</p>
  <footer class="blockquote-footer"> <cite title="Source Title">{{timepoint.date}}</cite></footer>
</blockquote>

gensec/blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% block content %}
{% load static %}

<div class="container">
    <div class="card-panel teal z-depth-4">
      <span class="white-text" style="font-size:150%;">This is a template for the proposed platform for a more transparent and engaging administration within the jurisdiction
      of General Secretary, which, I believe, should be brought forth irrespective of me being elected or not.
      </span>
      <br>
      <footer class="blockquote-footer" > <cite title="Source Title" style="font-size:120%;"> - Nihal Shetty, Contesting for General Secretary </cite></footer>

</div>
<br><br>
<div class="container">
   <div class="row">
    <div class="col s12 m5 " style="margin:2%;">
      <a class="waves-effect waves-light btn center-align z-depth-2" href="{% url 'blog:post_list' %}" style="background-color:rgb(104, 159, 242)">Suggestions/Complaints</a>
    </div>
    <div class="col s12 m5" style="margin:2%; ">
      <a class="waves-effect waves-light btn center-align z-depth-2" href="{% url 'blog:event_list' %}" style="background-color:rgb(104, 159, 242)">Ongoing Events</a>
    </div>
   </div>
</div>

</div>

<div class="row">
  <div class="col s12 m4">
    <div class="card z-depth-3" style="background-color:rgb(234, 96, 96);">
      <div class="container">
        <div class="card-content white-text">
          <i class="large material-icons" style="margin-left:30%;">accessibility</i>
          <span class="card-title" style="margin-left:25%;">Accessibilty</span>
        </div>
      </div>
    </div>
  </div>
  <div class="col s12 m4">
    <div class="card z-depth-3" style="background-color:rgb(234, 96, 96);">
      <div class="container">
        <div class="card-content white-text">
          <i class="large material-icons" style="margin-left:33%;">import_contacts</i>
          <span class="card-title" style="margin-left:25%;">Transparency</span>
        </div>
      </div>
    </div>
  </div>
  <div class="col s12 m4">
    <div class="card z-depth-3" style="background-color:rgb(234, 96, 96);">
      <div class="container">
        <div class="card-content white-text">
          <i class="large material-icons" style="margin-left:30%;">group</i>
          <span class="card-title" style="margin-left:25%;">Democracy</span>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container">


      <div class="card">
        <div class="card-image">
            <iframe class="center-align" style="width:100%; margin:3% 0px 3% 0px; height:30em;;" src="https://www.youtube.com/embed/BA45qSj30O4?list=PLLkjSCJXBvt_TrOP7tkckK1j4Jjui4C1f"  allow="autoplay; encrypted-media" allowfullscreen></iframe>
        </div>
        <div class="card-content">
          <p>
            <em style="font-family: 'Muli', sans-serif; font-size:150%;">"NITK is great, not because of individuals who go up on stage,
               but because of each and everyone of you!"
            </em>
          </p>
        </div>
      </div>

</div>


  <div class=" row">
    <div class="tdm-con">
      <div class="col s12 m6 l4 offset-l2" style="overflow:hidden;">
        <img src="{%static 'blog/images/shetty.jpeg' %}" alt="Poster here" class="tdm-con-img2 z-depth-4" style="margin-top:40%;">
      </div>

      <div class="container card-stacked col s12 m6 l4 tdm-content">
  <div class="card" style="width:100%;">
    <div class="card-content" style="font-family: 'Muli', sans-serif;">
          <h3>VISION </h3>
          <p class="flow-text">
            Hello, I am Nihal Shetty, one of the candidates contesting for the post of General Secretary.
            I believe, in order to create an administration not based on utopian promises, it is imperative that
            a platform such as this must exist. On this portal, students can view the current proceedings of matters
            in the jurisdiction of the General Secretary, as well as provide suggestions/post complaints.
          </p>

          <p class="flow-text">
            Let's face it, not every problem can be solved. But that does not mean you shouldn't know why.If elected,
            I intend to address as many as possible grievances/suggestions within my capabilities, and do either of the two -
            solve it, or tell you why it cannot be solved. Also, to maintain transparency, I shall try my best to keep you updated
            about the progress of ongoing work.
          </p>
    </div>

    <div class="card-content grey lighten-4" style="font-family: 'Muli', sans-serif;">
          <b class="flow-text">
           This elections, let's vote uninfluenced. Let's vote for NITK.
         </b>
    </div>
  </div>
      </div>
  </div>
  </div>
{% endblock %}

gensec/blog/templates/blog/post_detail.html
<div class="card post-detail">



  <div class="card-content post-detail-content">
    <div>
      <span class="card-title">{{post.title}}</span>
      <div class="chip float right">
        Implemented
        {% if post.implemented %}
        <i class="material-icons right" style="font-size:20px; margin-top:5%;">check</i>
        {% else %}
        <i class="material-icons right" style="font-size:20px; margin-top:5%;">clear</i>
        {% endif %}
      </div>

    </div>
    <br>
    <p>{{post.text}}</p>
  </div>



  <div class="card-reveal">
      <span class="card-title grey-text text-darken-4" >Comments<i class="material-icons right" >close</i></span>
    <div class="reveal-html">
        {% include "blog/comments.html" with comments=post.comments %}
    </div>
  </div>


  <div class="card-tabs">
    <ul class="tabs tabs-fixed-width">
      <li class="tab"><a class="upvote com">Upvote ({{post.upvote}})</a></li>
      <li class="tab"><a  class="comments activator com">Comments</a></li>
      <li class="tab"><a class="secretary modal-trigger com" href="#{{post.pk}}">Redressal</a></li>
    </ul>
  </div>

  <div id="{{post.pk}}" class="modal">
  <div class="modal-content">
    <h4>Secretary Says</h4>
    {% include "blog/secretary/secretary.html" with comments=post.comments post=post %}
  </div>
  <div class="modal-footer">
    <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">Okay!</a>
  </div>
</div>

  <script>
  $(document).ready(function(){
    $('.modal').modal();
  });
  </script>




</div>

gensec/blog/templates/blog/posts.html
{% extends "blog/base.html" %}


{% block content %}



<div class="container">
  <h2>Suggestions</h2>

  <div class="container suggestions-text">

  <div class="container">
    <h3 style="margin:2% 0 1% 5%;">What's this?</h3>
    <p class="text-usage">Students can drop their suggestions/complaints here, which shall regularly be addressed by the candidate.</p>
    <p class="text-usage">If a student happens to have a suggestion that's already posted, she may upvote it in order to increase its priority of redressal.</p>
    <p class="text-usage">The candidates opinion on a suggestion/ status of the work being done on it can be seen using 'secretary says'.</p>
  
    <h6 style="margin:2% 0 1% 5%;">NOTE: The upvote button has no functionalities, since this is just a template.</h6>
  </div>

  </div>

   {% for post in posts %}
       {% include "blog/post_detail.html" with post=post %}
   {% endfor %}
</div>

{% endblock %}

gensec/blog/templates/blog/secretary/secretary.html
{% for comment in comments.all %}
<div class="card">
  {% if comment.parent_comment %}

  <div class="card-content sec-card" style="padding:0px;">
    {% include "blog/comment_detail.html" with comment=comment %}
  </div>
  <div class="card-content sec-card grey lighten-4" style="padding:0px;">
      <p style="font-style:italic;"> In response to</p>
      {% include "blog/comment_detail.html" with comment=comment.parent_comment%}
  </div>

{% endif %}
</div>

<div class="card" style="background-color: rgb(199, 210, 226);">
  {% if comment.author.is_superuser and not comment.parent_comment %}
  <div class="card-content" style="padding:3px;">
    {% include "blog/comment_detail.html" with comment=comment %}
  </div>
  {% endif %}
</div>
{% endfor %}